pipeline {
    agent any
        stages{
            stage('Test sending mail plugin') {
                steps {
                    emailext body: 'Test Message',
                        subject: 'Test Subject',
                        to: 'ordinaltestuser@gmail.com'
                }
            }
        }
    }